#define CONFIG_PS2K_INITIAL_BUF_SIZE 4096
#define CONFIG_PS2K_ALLOC_BUF_MALLOC 1
#define CONFIG_PS2K_ALLOC_BUF 1
#define CONFIG_PIT_FREQUENCY 25
#define CONFIG_EXCEPTIONS_NESTING_THRESHOLD 3
#define CONFIG_EXCEPTIONS_RUN_DEBUGGER 1
